---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Archlinux
    image: archlinux:latest
    dockerfile: Dockerfile.j2
  # - name: Centos7
  #   image: docker.io/pycontribs/centos:7
  #   pre_build_image: true
  # - name: Debian9
  #   image: debian:stretch
  #   command: /sbin/init
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   privileged: yes
provisioner:
  name: ansible
verifier:
  name: ansible
